trigger:
  branches:
    include:
      - main

pr: none

variables:
  - group: celora-shared
  - name: NODE_VERSION
    value: '20.x'
  - name: IMAGE_NAME
    value: 'celora-web'
  - name: DEPLOY_ENV
    value: 'prod'

stages:
  - stage: Build
    displayName: "Build & Package"
    jobs:
      - job: build_and_package
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: 'Use Node.js $(NODE_VERSION)'

          - task: Cache@2
            inputs:
              key: 'npm | $(Agent.OS) | package-lock.json'
              restoreKeys: 'npm | $(Agent.OS)'
              path: '$(Pipeline.Workspace)/.npm'
            displayName: 'Cache npm'

          - script: npm ci
            displayName: 'Install dependencies'

          - script: npm run lint
            displayName: 'Run ESLint'
            continueOnError: false

          - script: npm run typecheck
            displayName: 'Run TypeScript checks'
            continueOnError: false

          - script: npm test -- --coverage --ci --maxWorkers=2
            displayName: 'Run Jest tests with coverage'
            continueOnError: false

          - script: npx playwright install --with-deps chromium
            displayName: 'Install Playwright browsers'

          - script: |
              npm run build
              npm start &
              sleep 10
              npm run test:e2e || true
              pkill -f "next start" || true
            displayName: 'Run E2E tests'
            continueOnError: true
            env:
              PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000
              SKIP_ENV_VALIDATION: 'true'

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
              failTaskOnFailedTests: true
            displayName: 'Publish test results'

          - task: PublishCodeCoverageResults@1
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
            displayName: 'Publish code coverage'

          - script: |
              set -euo pipefail
              if [ -f coverage/coverage-summary.json ]; then
                COVERAGE_LINES=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
                COVERAGE_FUNCTIONS=$(cat coverage/coverage-summary.json | jq -r '.total.functions.pct')
                COVERAGE_BRANCHES=$(cat coverage/coverage-summary.json | jq -r '.total.branches.pct')
                COVERAGE_STATEMENTS=$(cat coverage/coverage-summary.json | jq -r '.total.statements.pct')
                
                echo "##[section]Code Coverage Report"
                echo "Lines: $COVERAGE_LINES%"
                echo "Functions: $COVERAGE_FUNCTIONS%"
                echo "Branches: $COVERAGE_BRANCHES%"
                echo "Statements: $COVERAGE_STATEMENTS%"
                
                THRESHOLD=70
                FAILED=false
                
                if (( $(echo "$COVERAGE_LINES < $THRESHOLD" | bc -l) )); then
                  echo "##vso[task.logissue type=error]Lines coverage ($COVERAGE_LINES%) is below $THRESHOLD% threshold"
                  FAILED=true
                fi
                if (( $(echo "$COVERAGE_FUNCTIONS < $THRESHOLD" | bc -l) )); then
                  echo "##vso[task.logissue type=error]Functions coverage ($COVERAGE_FUNCTIONS%) is below $THRESHOLD% threshold"
                  FAILED=true
                fi
                if (( $(echo "$COVERAGE_BRANCHES < $THRESHOLD" | bc -l) )); then
                  echo "##vso[task.logissue type=error]Branches coverage ($COVERAGE_BRANCHES%) is below $THRESHOLD% threshold"
                  FAILED=true
                fi
                if (( $(echo "$COVERAGE_STATEMENTS < $THRESHOLD" | bc -l) )); then
                  echo "##vso[task.logissue type=error]Statements coverage ($COVERAGE_STATEMENTS%) is below $THRESHOLD% threshold"
                  FAILED=true
                fi
                
                if [ "$FAILED" = true ]; then
                  exit 1
                fi
              else
                echo "##vso[task.logissue type=warning]Coverage summary file not found"
              fi
            displayName: 'Enforce coverage threshold (70% all metrics)'
            continueOnError: false

          - script: npm run generate:openapi
            displayName: 'Generate OpenAPI specification'
            continueOnError: false

          - script: npm run build
            displayName: 'Build Next.js app + Service Worker'
            continueOnError: false

          - script: npm run build:extension
            displayName: 'Build browser extension'
            continueOnError: false

          - script: |
              set -euo pipefail
              mkdir -p $(Build.ArtifactStagingDirectory)
              tar -czf $(Build.ArtifactStagingDirectory)/celora-pwa.tgz .next package.json package-lock.json
            displayName: 'Bundle PWA build artifact'

          - script: |
              set -euo pipefail
              if [ -d extension ]; then
                cd extension
                zip -r ../$(Build.ArtifactStagingDirectory)/celora-extension.zip manifest.json popup.html popup.css dist
              fi
            displayName: 'Zip browser extension'

          - script: |
              set -euo pipefail
              if [ -f docs/openapi.json ]; then
                cp docs/openapi.json $(Build.ArtifactStagingDirectory)/openapi.json
                echo "OpenAPI spec copied to artifacts"
              fi
            displayName: 'Copy OpenAPI specification to artifacts'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'celora-artifacts'
            displayName: 'Publish build artifacts'

  - stage: DeployStaging
    displayName: "Deploy to Staging"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: deploy_to_staging
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: celora-artifacts
                  displayName: 'Download build artifacts'

                - task: NodeTool@0
                  inputs:
                    versionSpec: $(NODE_VERSION)
                  displayName: 'Use Node.js $(NODE_VERSION)'

                - task: AzureKeyVault@2
                  inputs:
                    azureSubscription: '$(AZURE_SUBSCRIPTION)'
                    KeyVaultName: '$(KEY_VAULT_NAME_STAGING)'
                    SecretsFilter: 'DATABASE_URL,MSAL-CLIENT-ID,MSAL-CLIENT-SECRET'
                  displayName: 'Fetch secrets from Key Vault (Staging)'

                - script: |
                    cd $(Pipeline.Workspace)/celora-artifacts
                    tar -xzf celora-pwa.tgz
                    npm ci --production
                  displayName: 'Extract and install dependencies'

                - script: |
                    cd $(Pipeline.Workspace)/celora-artifacts
                    npx prisma migrate deploy
                  env:
                    DIRECT_DATABASE_URL: $(DATABASE_URL)
                  displayName: 'Run Prisma database migrations'
                  continueOnError: false

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: '$(AZURE_SUBSCRIPTION)'
                    appType: 'webAppLinux'
                    appName: '$(AZURE_WEBAPP_NAME_STAGING)'
                    package: '$(Pipeline.Workspace)/celora-artifacts/celora-pwa.tgz'
                    runtimeStack: 'NODE|20-lts'
                    startUpCommand: 'npm start'
                  displayName: 'Deploy to Staging Web App'

                - script: |
                    echo "##[section]Staging Deployment Summary"
                    echo "App URL: https://$(AZURE_WEBAPP_NAME_STAGING).azurewebsites.net"
                    echo "OpenAPI: https://$(AZURE_WEBAPP_NAME_STAGING).azurewebsites.net/docs/openapi.json"
                  displayName: 'Staging deployment summary'

  - stage: DeployProduction
    displayName: "Deploy to Production"
    dependsOn: DeployStaging
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: deploy_to_production
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: celora-artifacts
                  displayName: 'Download build artifacts'

                - task: NodeTool@0
                  inputs:
                    versionSpec: $(NODE_VERSION)
                  displayName: 'Use Node.js $(NODE_VERSION)'

                - task: AzureKeyVault@2
                  inputs:
                    azureSubscription: '$(AZURE_SUBSCRIPTION)'
                    KeyVaultName: '$(KEY_VAULT_NAME_PROD)'
                    SecretsFilter: 'DATABASE_URL,MSAL-CLIENT-ID,MSAL-CLIENT-SECRET'
                  displayName: 'Fetch secrets from Key Vault (Production)'

                - script: |
                    cd $(Pipeline.Workspace)/celora-artifacts
                    tar -xzf celora-pwa.tgz
                    npm ci --production
                  displayName: 'Extract and install dependencies'

                - script: |
                    cd $(Pipeline.Workspace)/celora-artifacts
                    npx prisma migrate deploy
                  env:
                    DIRECT_DATABASE_URL: $(DATABASE_URL)
                  displayName: 'Run Prisma database migrations'
                  continueOnError: false

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: '$(AZURE_SUBSCRIPTION)'
                    appType: 'webAppLinux'
                    appName: '$(AZURE_WEBAPP_NAME_PROD)'
                    package: '$(Pipeline.Workspace)/celora-artifacts/celora-pwa.tgz'
                    runtimeStack: 'NODE|20-lts'
                    startUpCommand: 'npm start'
                  displayName: 'Deploy to Production Web App'

                - script: |
                    echo "##[section]Production Deployment Summary"
                    echo "App URL: https://$(AZURE_WEBAPP_NAME_PROD).azurewebsites.net"
                    echo "OpenAPI: https://$(AZURE_WEBAPP_NAME_PROD).azurewebsites.net/docs/openapi.json"
                  displayName: 'Production deployment summary'
