trigger: none
pr: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: prod
  - name: action
    displayName: Terraform action
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy
  - name: varFile
    displayName: Terraform var-file
    type: string
    default: infra/terraform/environments/prod.tfvars

variables:
  - group: celora-shared

stages:
  - stage: Terraform
    displayName: Terraform $(parameters.action)
    jobs:
      - job: RunTerraform
        displayName: "Terraform $(parameters.action)"
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            persistCredentials: true

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.7.5'

          - task: AzureCLI@2
            displayName: 'Terraform $(parameters.action)'
            inputs:
              azureSubscription: 'Azure-$(parameters.environment)'
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
              inlineScript: |
                set -euo pipefail

                echo "Initializing Terraform backend"
                terraform init \
                  -backend-config="resource_group_name=$(INFRA_STATE_RG)" \
                  -backend-config="storage_account_name=$(INFRA_STATE_STORAGE)" \
                  -backend-config="container_name=$(INFRA_STATE_CONTAINER)" \
                  -backend-config="key=$(INFRA_STATE_KEY)"

                case "${{ parameters.action }}" in
                  plan)
                    terraform plan -var-file="${{ parameters.varFile }}" -out=tfplan -input=false
                    ;;
                  apply)
                    terraform plan -var-file="${{ parameters.varFile }}" -out=tfplan -input=false
                    terraform apply -input=false tfplan
                    ;;
                  destroy)
                    terraform destroy -var-file="${{ parameters.varFile }}" -auto-approve -input=false
                    ;;
                  *)
                    echo "Unsupported action"
                    exit 1
                    ;;
                esac
